version: '3.9'
services:
  web:
    build: .
    ports:
      - "4040:8000"
    volumes:
      - ./staticfiles:/app/staticfiles
    env_file:
      - .env
    environment:
      MINIO_ACCESS_KEY: "M0P0pT0ShSorWYCpePCi"
      MINIO_SECRET_KEY: "E0k68nU1A1VYJtVSKI3Eh7VMIPlJ5znmk9ib0LEF"
      MINIO_BUCKET: "shikala"
      MINIO_ENDPOINT: "https://minio.shikala.com"
