version: '3.9'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "4040:8000"
    volumes:
      - ./staticfiles:/var/www/shikala/staticfiles
    env_file:
      - .env
